function LoadGUI(gui)
%UNTITLED3 Summary of this function goes here
%   Detailed explanation goes here
spaceY = 0.05;
x = 0.05;
y = 0.8;
yBetween = 0.1;
L = Loads;

LoadArea = uipanel('Parent',gui.Figure,'Position',[0,0,1,1]);

TextInput = uicontrol(LoadArea,'Style','text',...
    'String','Pick your Calculator(s)','Units','normalized',...
    'FontSize',19,'Position',[x,y,0.9,spaceY]);

SSBy = y-yBetween;
SSBx1 = 0.5;
SSBx2 = 0.2;
CheckSSB = uicontrol(LoadArea,'Style','checkbox',...
    'String','Simply Supported Beam','FontSize',14,...
    'Units','normalized','Position',[x,SSBy,SSBx1,spaceY]);
TextSSB = uicontrol(LoadArea,'Style','text',...
    'String','Load (lbF):','Units','normalized','FontSize',14,...
    'Position',[x+SSBx1,SSBy-0.01,SSBx2,spaceY]);
InputSSB = uicontrol(LoadArea,'Style','edit',...
    'Max',1,'Min',1,'BackgroundColor','white',...
    'Units','normalized','FontSize',14,...
    'Position',[x+SSBx1+SSBx2,SSBy,SSBx2,spaceY]);

CBy = SSBy-yBetween;
CBx1 = 0.5;
CBx2 = 0.2;
CheckCB = uicontrol(LoadArea,'Style','checkbox',...
    'String','Cantilevered Beam','FontSize',14,...
    'Units','normalized','Position',[x,CBy,CBx1,spaceY]);
TextCB = uicontrol(LoadArea,'Style','text',...
    'String','Load (lbF):','Units','normalized','FontSize',14,...
    'Position',[x+CBx1,CBy-0.01,CBx2,spaceY]);
InputCB = uicontrol(LoadArea,'Style','edit',...
    'Max',1,'Min',1,'BackgroundColor','white',...
    'Units','normalized','FontSize',14,...
    'Position',[x+CBx1+CBx2,CBy,CBx2,spaceY]);

By = CBy-yBetween;
Bx1 = 0.5;
Bx2 = 0.2;
CheckB = uicontrol(LoadArea,'Style','checkbox',...
    'String','Buckling & Compression','FontSize',14,...
    'Units','normalized','Position',[x,By,Bx1,spaceY]);
TextB = uicontrol(LoadArea,'Style','text',...
    'String','Load (lbF):','Units','normalized','FontSize',14,...
    'Position',[x+Bx1,By-0.01,Bx2,spaceY]);
InputB = uicontrol(LoadArea,'Style','edit',...
    'Max',1,'Min',1,'BackgroundColor','white',...
    'Units','normalized','FontSize',14,...
    'Position',[x+Bx1+Bx2,By,Bx2,spaceY]);

Ny = By-0.06;
Nx1 = 0.5;
Nx2 = 0.2;
spaceYN = 0.06;
TextN = uicontrol(LoadArea,'Style','text',...
    'String','n','Units','normalized','FontSize',14,...
    'Position',[x+Nx1,Ny,Nx2,spaceY]);
InputN = uicontrol(LoadArea,'Style','popupmenu',...
    'String',{'4','2','1','.25'},'Value',1,'FontSize',14,...
    'BackgroundColor','white','Units','normalized',...
    'Position',[x+Nx1+Nx2,Ny,Nx2,spaceY]);
Ex = get(CheckB,'Extent');
buttonN = uicontrol(LoadArea,'Style','pushbutton',...
    'String','Look up n values','Units','normalized',...
    'FontSize',14,...
    'Position',[x,0.46,Ex(3),0.04],'Callback',{@nValues});
    function nValues(~,~)
        currentFolder = pwd;
        imageLoc = '\Images\nValues.png';
        s = strcat(currentFolder,imageLoc);
        I = imread(s);
        n = figure('Name','nValues');
        imshow(I)
    end

Ty = Ny-yBetween;
Tx1 = 0.5;
Tx2 = 0.2;
CheckT = uicontrol(LoadArea,'Style','checkbox',...
    'String','Torsion & Torsional Buckling','FontSize',14,...
    'Units','normalized','Position',[x,Ty,Tx1,spaceY]);
TextT = uicontrol(LoadArea,'Style','text',...
    'String','Torque (in*lb):','Units','normalized','FontSize',14,...
    'Position',[x+Tx1,Ty+0.005,Tx2,spaceY]);
InputT = uicontrol(LoadArea,'Style','edit',...
    'Max',1,'Min',1,'BackgroundColor','white',...
    'Units','normalized','FontSize',14,...
    'Position',[x+Tx1+Tx2,Ty,Tx2,spaceY]);

addlistener(gui,'Compute',@ScrapeLoad);
    function ScrapeLoad(~,~)
        L.SSB = get(CheckSSB,'Value');
        L.SSBLoad = str2double(get(InputSSB,'String'));
        L.CB = get(CheckCB,'Value');
        L.CBLoad = str2double(get(InputCB,'String'));
        L.B = get(CheckB,'Value');
        L.BLoad = str2double(get(InputB,'String'));
        Temp = get(InputN,'String');
        L.Bn =  str2double(Temp{get(InputN,'Value')});
        L.T = get(CheckT,'Value');
        L.TTorque = str2double(get(InputT,'String'));
        set(LoadArea,'Units','Normalized','Position',[0 0 .333 1]);
    end
Next = uicontrol(LoadArea,'Style','pushbutton',...
    'String','Choose Material','Units','normalized',...
    'FontSize',20,...
    'Position',[0.25,0.16,0.5,0.1],'Callback',{@OpenMaterial});
    function OpenMaterial(~,~)
        %Change area of Loads section because figure expanded
        set(LoadArea,'Units','Normalized','Position',[0 0 .5 1]);
        MaterialGUI(gui,L);
        set(Next,'Enable','Off');
    end
end